### ISSUE TITLE
When is the dataset being published?

### ISSUE THREAD

**Issue by haztecaso** [xyfrieder/science-GHOSTS#1]
Hi, I've read the paper on [Mathematical Capabilities of ChatGPT](https://arxiv.org/abs/2301.13867) and I'm very curious on seeing the GHOSTS dataset and if possible trying to use it in some way.

Will you publish it soon?

Thanks a lot!

**Comment by notesbymuneeb** [comment]
I am also curious to see the results. Waiting for it!

**Comment by PsoriasiIR** [comment]
+1 Waiting for it!

**Comment by peterdunson** [comment]
I emailed and was told that it will be coming in the next few weeks, they're having issues with copyrights.
