### ISSUE TITLE
Missing prompts? 

### ISSUE THREAD

**Issue by fayolle** [xyfrieder/science-GHOSTS#2]
@friederrr It seems that all the prompts for Munkres 1&2, Olympiad, Durrett's probability, and Rudin 1& 2 are missing (empty fields in the json files) for all the data-sets. 
For example: 
https://github.com/friederrr/GHOSTS/blob/680da88564708d57dac1041f7add6be45f0a4bc5/dataset_30jan/J.%20Munkres%2C%20Topology%20(ch.%201).json#L3

**Comment by friederrr** [comment]
It's not missing, it's copyrighted, so we can't include it (was we mentioned in the paper, please have a look)

**Comment by fayolle** [comment]
Thank you. Sorry I didn't pay enough attention to this part (first paragraph of B.3). 
It is funny, though, because these books are easily found on internet and were likely part of the training data of these LLMs.

**Comment by friederrr** [comment]
No worries :) 

Yes, the internet is a big place - and while we were not able to include the prompts, unfortunately, there is the "ref" field to reconstruct exactly the page/exercise from where we took them.
